// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Day01.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string Name { get; set; }

}